// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLZ3Q7qBMFk3TRdClrq0F-yrTpZo9U4m4',
    appId: '1:312168652736:web:eef7151bdf1d085c4b7225',
    messagingSenderId: '312168652736',
    projectId: 'chat-app-de00d',
    authDomain: 'chat-app-de00d.firebaseapp.com',
    storageBucket: 'chat-app-de00d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtLDAC8vTaEf5A8ueZS7i5oZj4qKknf84',
    appId: '1:312168652736:android:2fec13afdfed550c4b7225',
    messagingSenderId: '312168652736',
    projectId: 'chat-app-de00d',
    storageBucket: 'chat-app-de00d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_J6xeeIk3IMDZ-c1sCxCqBVVqu6inWlw',
    appId: '1:312168652736:ios:abff9bb1b3c0be534b7225',
    messagingSenderId: '312168652736',
    projectId: 'chat-app-de00d',
    storageBucket: 'chat-app-de00d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_J6xeeIk3IMDZ-c1sCxCqBVVqu6inWlw',
    appId: '1:312168652736:ios:abff9bb1b3c0be534b7225',
    messagingSenderId: '312168652736',
    projectId: 'chat-app-de00d',
    storageBucket: 'chat-app-de00d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLZ3Q7qBMFk3TRdClrq0F-yrTpZo9U4m4',
    appId: '1:312168652736:web:83f7be878279a4bb4b7225',
    messagingSenderId: '312168652736',
    projectId: 'chat-app-de00d',
    authDomain: 'chat-app-de00d.firebaseapp.com',
    storageBucket: 'chat-app-de00d.appspot.com',
  );
}
